#!/usr/bin/env bash
#
# Checks that the dependencies are in a good state for commiting the main repository

#echo Running $BASH_SOURCE
#set | egrep GIT
#echo PWD is $PWD
#echo cwd is $(pwd)

# Have to run in a clean environment, because dependencies are also git projects and have different settings
env -i dependencies/check_commit.sh
if [ $? -ne 0 ]
then
    exit 1
fi
exit 0
