#!/bin/sh
source=src/gci
dest=${0%import_molpro}
if [ -r $source ]; then
    files=$(ls $source/*.{cpp,h} $source/../global/{memory,smat,Profiler}.*)
    cp $files $dest
else
    echo "Not in molpro source tree"
    exit 1
fi
